version: '3.3'
name: graduation-phase-one
services:
  api:
    image: ${DOCKER_REGISTRY-}api
    networks:
      - backend
    build:
      context: ../
      dockerfile: ./src/api/PoliceDepartment.EvidenceManager.API/Dockerfile
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5015:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  mvc:
    image: ${DOCKER_REGISTRY-}mvc
    networks:
      - backend
    build:
      context: ../
      dockerfile: ./src/web/PoliceDepartment.EvidenceManager.MVC/Dockerfile
    container_name: mvc
    depends_on:
      - api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5020:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
networks:
  backend:
    driver: bridge